apiVersion: batch/v1
kind: CronJob
metadata:
  name: quakewatch-health-check
spec:
  schedule: "*/2 * * * *" # run every 2 minutes
  successfulJobsHistoryLimit: 3 # keep the last 3 successful Jobs
  failedJobsHistoryLimit: 3 # keep the last 3 failed Jobs
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: health-check
              image: busybox:1.36
              command:
                - /bin/sh
                - -c
                - |
                  echo "Checking QuakeWatch service..."
                  if wget -qO- -T 5 http://quakewatch-service.default.svc.cluster.local:80/ > /dev/null; then
                    echo "QuakeWatch service is UP"
                    exit 0
                  else
                    echo "QuakeWatch service is DOWN"
                    exit 1
                  fi
          restartPolicy: OnFailure
