name: CI

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install Python dependencies and pylint
        working-directory: QuakeWatch
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run pylint
        working-directory: QuakeWatch
        run: |
          pylint app.py dashboard.py utils.py \
            --disable=missing-module-docstring,missing-class-docstring,missing-function-docstring,wrong-import-position,wrong-import-order,line-too-long,missing-timeout,no-else-return,too-many-locals,redefined-outer-name,logging-fstring-interpolation,import-outside-toplevel \
            --fail-under=5

      - name: Build Docker image
        run: |
          docker build -t quakewatch-ci:latest ./QuakeWatch
